services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test:
        ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\""]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
    command: ["npm", "start"]
    environment:
      PORT: 4000
      MONGO_URL: mongodb://mongo:27017/nosh-farmaiye
      JWT_SECRET: "716e6f70c53e454e8f454a39893b4b9a06c7862c485129ff54cfb8d09f58b891495696296d5f0c2c42d5cc952c73471b141f12a77fbdaab77f0404238a8fe73f"
      SALT: "10"
      STRIPE_SECRET_KEY: "sk_test_#"
      ALLOWED_ORIGINS: "http://localhost,http://127.0.0.1,http://localhost:5173,http://localhost:5174"
      FRONTEND_URL: "http://localhost:5173"
      ADMIN_URL: "http://localhost:5174"
      CURRENCY: "INR"
      DELIVERY_FEE: "99"
      ADMIN_EMAIL: "admin@noshfarmaiye.com"
      ADMIN_PASSWORD: "Chef@2025!"
      ADMIN_NAME: "Nosh Admin"
      ADMIN_FORCE_RESET: "false"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
    ports:
      - "4000:4000"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://localhost:4000/ > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:4000
        VITE_BRAND_NAME_EN: "Nosh Farmaiye"
        VITE_BRAND_NAME_HI: "Nosh फ़रमाइए"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5173:80"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1/ > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  admin:
    build:
      context: .
      dockerfile: docker/admin.Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:4000
        VITE_BRAND_NAME_EN: "Nosh Farmaiye"
        VITE_BRAND_NAME_HI: "Nosh फ़रमाइए"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - "5174:80"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -qO- http://127.0.0.1/ > /dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

volumes:
  mongo-data:
